// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxOWI3d3PcsrJzJBcl8LGYJ-f7OluQqxA',
    appId: '1:664484860099:web:6bee55f7d5fab97ac51276',
    messagingSenderId: '664484860099',
    projectId: 'webrtc-real-time-communication',
    authDomain: 'webrtc-real-time-communication.firebaseapp.com',
    storageBucket: 'webrtc-real-time-communication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc7XoB2qfdsn6569UX_LKXlh0K2TB_evE',
    appId: '1:664484860099:ios:a48f34c5199beae6c51276',
    messagingSenderId: '664484860099',
    projectId: 'webrtc-real-time-communication',
    storageBucket: 'webrtc-real-time-communication.firebasestorage.app',
    iosBundleId: 'com.example.testVideoAppFirebase',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72hHCsg2wMU4QfHiUi9ubx8noJdCiwJw',
    appId: '1:664484860099:android:45397d7217c5c637c51276',
    messagingSenderId: '664484860099',
    projectId: 'webrtc-real-time-communication',
    storageBucket: 'webrtc-real-time-communication.firebasestorage.app',
  );

}